#!/usr/bin/env python3

import sys
import numpy as np
import pandas as pd


usage_message = '''Gets the output from the dumpfile generated by the cONNXr

Usage:
\tget_connxr_output.py <path_to_dumpfile.txt> <path_to_output_file.csv>
'''


dump_file_path = ''
output_file_path = ''

if '-h' in sys.argv:
    print(usage_message)
    sys.exit(0)

elif len(sys.argv) != 3:
    print(usage_message)
    sys.exit(1)

else:
    dump_file_path = sys.argv[1]
    output_file_path = sys.argv[2]

    with open(dump_file_path, 'r') as dump_file:
        lines = dump_file.readlines()
        index = 0
        
        for name, shape, tensor in zip(lines[0::3], lines[1::3], lines[2::3]):
            name = name.replace("name=", "").strip()
            shape = shape.replace("shape=", "").split(",")[:-1]    #remove last empty element
            tensor = tensor.replace("tensor=", "").split(",")[:-1] #remove last empty element

            # cast values
            shape = [int(i) for i in shape]
            tensor = [float(i) for i in tensor]

            if name == 'dense_5':
                
                num_rows = int(len(tensor)/6)                
                output_tensor = np.asanyarray(tensor).reshape(num_rows, 6)

                print(f'Number of rows: {num_rows}')
                print(f'Output shape: {output_tensor.shape}')


    # np.savetxt(output_file_path, output_tensor, delimiter=',')
    pd.DataFrame(output_tensor).to_csv(output_file_path, header=False, mode='w', index=False)
    sys.exit(0)